version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: tax_engine_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tax_engine
      MYSQL_USER: taxuser
      MYSQL_PASSWORD: taxpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tax_engine_network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: tax_engine_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tax_engine_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tax_engine_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://taxuser:taxpassword@db:3306/tax_engine
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads
    depends_on:
      - db
      - redis
    networks:
      - tax_engine_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tax_engine_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - tax_engine_network

volumes:
  mysql_data:
  redis_data:
  uploaded_files:

networks:
  tax_engine_network:
    driver: bridge